spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_vendor?useSSL=false&allowPublicKeyRetrieval=true    
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  # JPA settings
  jpa:
    hibernate:
      ddl_auto: create